name: playground

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Playground in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Build
        run: |
          yarn
          npm run build

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: playground
          path: ./dist

  release:
    name: Release to Github
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master') && github.repository == 'release-lab/release-lab.github.io'
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: playground
          path: ./dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./dist # The folder the action should deploy.
          git-config-name: Github Action
